### ISSUE TITLE
Faire que les vidéo header fonction sur tout les navigateur de la meme maniere que sur firefox desktop

### ISSUE THREAD

**Issue by stupmedia** [stupmedia/website#5]
Faire que les vidéo header fonction comme sur firefox (desktop) (trop stylé)

**Comment by Geekatori** [comment]
Je n'ai pu faire le test que sur Firefox et Safari, mais je n'ai pas vu de différence. 
Quel est le résultat attendu ?

**Comment by stupmedia** [comment]
Firefox offre des fonctionalité pluplemntaire :
-PIP de la vidéo
-Player Dedier

Vidéo qui montre les differentes fonctionalités:
https://drive.google.com/file/d/1E9UEP0AasKA-r-fARMhajAidcIAwIeWz/view?usp=sharing

**Comment by Geekatori** [comment]
Les fonctionnalités de PIP et de player dédié sont spécifiques à chaque navigateur malheureusement.
Il existe peut-être des plugin de player qui font ça, mais ça risque d'alourdir tes pages
